### ISSUE TITLE
getConfig and getLimits infinitely calling themselves breaks testing when mtwitter is used as a client lib

### ISSUE THREAD

**Issue by TheAlphaNerd** [passcod/mtwitter#10]
Currently trying to use mtwitter and finding that my test suite never ends and then throws up.

I think I have managed to trace this back to the way in which getConfig / getLimits is being called. Due to the setTimeout infinte loop going on your program technically never ends.

Sad boi over here :(

Trying to think of an elegant way to clean this up.

**Comment by passcod** [comment]
Hi. mtwitter is unmaintained. Use [twitter](https://www.npmjs.com/package/twitter) or [twit](https://www.npmjs.com/package/twit).

**Comment by TheAlphaNerd** [comment]
I ended up hand rolling something

Neither of the other modules offer application mode.

**Comment by passcod** [comment]
I commented on issues on the two projects mentioned above: desmondmorris/node-twitter#81 and ttezel/twit#100.

It does look like there is _still_ not any really maintained twitter library in the Node.js ecosystem :( Hopefully someone(s) will step up one day

**Comment by passcod** [comment]
desmondmorris/node-twitter#94 implemented app-only auth!
