### ISSUE TITLE
How to shutdown the client?

### ISSUE THREAD

**Issue by luto** [passcod/mtwitter#6]
When I start the few lines of code below, nodejs never exits. That suggests that there is some kind of network connecting being held open. How can I fully exit the client?

```javascript
var Twitter = require('mtwitter');

var twit = new Twitter({
  consumer_key: '',
  consumer_secret: '',
  access_token_key: '',
  access_token_secret: ''
});
```

**Comment by passcod** [comment]
This library is unmaintained. Use [twitter](https://www.npmjs.com/package/twitter) or [twit](https://www.npmjs.com/package/twit) instead.
