### ISSUE TITLE
HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by alexeygritsenko** [passcod/mtwitter#9]
Hi, I have an error when sending a post to twitter. As your example code used unchanged, but the module does not work (

VS Run Log:
> Debugger listening on port 5858
{ [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' } undefined
undefined undefined
awesome: undefined
awesome: undefined

**Comment by passcod** [comment]
Hi. mtwitter is unmaintained. Use [twitter](https://www.npmjs.com/package/twitter) or [twit](https://www.npmjs.com/package/twit).
